import type { Metadata } from 'next';
import { Section, SectionHeading } from '@/components/ui/Section';
import { DiscoveryOutputView } from '@/components/discovery/DiscoveryOutput';
import { generateDiscoveryOutput } from '@/lib/discovery';
import type { DiscoveryAnswers } from '@/types/portal';

export const metadata: Metadata = {
  title: 'Proposal Preview',
  description: 'A sample Auto Growth OS proposal generated by the discovery engine.',
};

const SAMPLE: DiscoveryAnswers = {
  dealership: 'North Star Motors',
  city: 'Mississauga',
  businessType: 'dealership',
  inventoryModel: 'owned',
  inventoryWorkflow: 'spreadsheet',
  leadRouting: 'multiple_internal',
  aiLevel: 'human_approved',
  adsLevel: 'multi',
  websiteFeatures: ['city_pages', 'finance_pages', 'structured_data'],
  socialLevel: 'reels',
  access: ['website', 'domain', 'hosting', 'gbp', 'crm'],
  urgency: 'this_quarter',
};

export default function ProposalPreviewPage() {
  const output = generateDiscoveryOutput(SAMPLE);
  return (
    <div className="py-12 sm:py-16">
      <Section>
        <SectionHeading
          eyebrow="Proposal preview"
          title="A sample Auto Growth OS proposal"
          description="Generated by the discovery engine — this is what a dealership receives after discovery."
        />
        <div className="mt-8">
          <DiscoveryOutputView output={output} />
        </div>
      </Section>
    </div>
  );
}
