#!/usr/bin/env python3
"""Cognitia file-based goal-loop harness — isolated MVP.

Pure stdlib. No network. No message sending. Deterministic.
This is a SANDBOX/MOCK prototype only (see GUARDRAILS hard-stop #7).

Loop:  load goals -> plan steps -> guardrail-check each step ->
       execute via MOCK executor -> append to action ledger ->
       evaluate goal -> emit checkpoint report.

Run:
    python3 harness_mvp.py --goals goals.example.json --out ./run_output
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from datetime import datetime, timezone

# --------------------------------------------------------------------------
# Hard-stop boundary list. A step whose `action` (or any token in its
# `args.intent`) matches one of these is REFUSED before execution. Mirrors
# cognitia/loop/GUARDRAILS.md hard-stop boundaries.
# --------------------------------------------------------------------------
HARD_STOP_ACTIONS = frozenset(
    {
        "token_launch",
        "provide_liquidity",
        "promise_returns",
        "outreach_lead",
        "launch_paid_ad",
        "send_whatsapp",
        "send_sms",
        "send_email",
        "implement_vendor_adapter",
        "store_pii",
        "guarantee_roi",
    }
)

# Deterministic fixed clock so runs/reports are reproducible. Override via
# COGNITIA_HARNESS_NOW (ISO-8601) only for tests; default is fixed.
_DEFAULT_NOW = "2026-06-20T00:00:00+00:00"


def now_iso() -> str:
    return os.environ.get("COGNITIA_HARNESS_NOW", _DEFAULT_NOW)


# --------------------------------------------------------------------------
# MOCK executors. None of these touch the network or send anything. Each
# returns a deterministic, hash-stable result dict. Pure functions of input.
# --------------------------------------------------------------------------
def _stable_hash(payload: object) -> str:
    blob = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(blob).hexdigest()[:16]


def exec_research(args: dict) -> dict:
    """MOCK research: returns a synthetic, deterministic finding summary."""
    topic = args.get("topic", "unspecified")
    return {
        "kind": "research",
        "topic": topic,
        "summary": f"[MOCK] synthetic findings for topic={topic!r}",
        "evidence_count": len(str(topic)) % 5,
        "result_hash": _stable_hash({"research": topic}),
    }


def exec_draft_artifact(args: dict) -> dict:
    """MOCK artifact draft: returns deterministic synthetic artifact text."""
    name = args.get("name", "artifact")
    body = f"[MOCK ARTIFACT: {name}] generated by harness, no network used."
    return {
        "kind": "draft_artifact",
        "name": name,
        "chars": len(body),
        "body_preview": body[:60],
        "result_hash": _stable_hash({"artifact": name}),
    }


def exec_noop(args: dict) -> dict:
    """MOCK no-op: succeeds, changes nothing. Used for idempotency tests."""
    return {"kind": "noop", "result_hash": _stable_hash({"noop": args.get("tag", "")})}


# Any executor not registered here is treated as unknown -> step fails (not
# a guardrail block, an execution error). This keeps the registry explicit.
EXECUTORS = {
    "research": exec_research,
    "draft_artifact": exec_draft_artifact,
    "noop": exec_noop,
}


# --------------------------------------------------------------------------
# Guardrail check
# --------------------------------------------------------------------------
def guardrail_check(step: dict) -> tuple[bool, str]:
    """Return (allowed, reason). Blocks hard-stop actions and PII-laden args."""
    action = step.get("action", "")
    if action in HARD_STOP_ACTIONS:
        return False, f"action {action!r} is on the hard-stop list"
    intent = str(step.get("args", {}).get("intent", "")).lower()
    for blocked in HARD_STOP_ACTIONS:
        if blocked.replace("_", " ") in intent or blocked in intent:
            return False, f"intent references hard-stop {blocked!r}"
    return True, "ok"


# --------------------------------------------------------------------------
# Action ledger — append-only JSON-lines writer.
# --------------------------------------------------------------------------
class Ledger:
    def __init__(self, path: str):
        self.path = path
        self._seq = 0
        # Resume sequence if a ledger already exists (append-only contract).
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as fh:
                self._seq = sum(1 for line in fh if line.strip())

    def append(self, record: dict) -> dict:
        self._seq += 1
        entry = {"seq": self._seq, "ts": now_iso(), **record}
        os.makedirs(os.path.dirname(self.path) or ".", exist_ok=True)
        with open(self.path, "a", encoding="utf-8") as fh:
            fh.write(json.dumps(entry, sort_keys=True) + "\n")
        return entry

    def read_all(self) -> list:
        if not os.path.exists(self.path):
            return []
        with open(self.path, "r", encoding="utf-8") as fh:
            return [json.loads(line) for line in fh if line.strip()]


# --------------------------------------------------------------------------
# Loader
# --------------------------------------------------------------------------
def load_goals(path: str) -> list:
    with open(path, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    goals = data.get("goals", [])
    if not isinstance(goals, list):
        raise ValueError("goals file must contain a 'goals' list")
    return goals


# --------------------------------------------------------------------------
# Core loop
# --------------------------------------------------------------------------
def run_step(step: dict, ledger: Ledger) -> dict:
    """Guardrail-check, then execute (or refuse), then ledger-append."""
    step_id = step.get("id", "unknown")
    action = step.get("action", "")
    args = step.get("args", {})

    allowed, reason = guardrail_check(step)
    if not allowed:
        return ledger.append(
            {
                "step_id": step_id,
                "action": action,
                "status": "BLOCKED",
                "guardrail_reason": reason,
                "classification": "UNSAFE",
            }
        )

    executor = EXECUTORS.get(action)
    if executor is None:
        return ledger.append(
            {
                "step_id": step_id,
                "action": action,
                "status": "ERROR",
                "error": f"no MOCK executor registered for action {action!r}",
                "classification": "INFERRED",
            }
        )

    result = executor(args)
    return ledger.append(
        {
            "step_id": step_id,
            "action": action,
            "status": "OK",
            "result": result,
            "classification": "VERIFIED",
        }
    )


def run_goal(goal: dict, ledger: Ledger) -> dict:
    """Plan = the goal's declared steps (no LLM in MVP). Execute each."""
    goal_id = goal.get("id", "unknown")
    steps = goal.get("steps", [])
    entries = [run_step(s, ledger) for s in steps]
    statuses = [e["status"] for e in entries]
    if "BLOCKED" in statuses:
        goal_status = "PARTIAL_BLOCKED"
    elif "ERROR" in statuses:
        goal_status = "PARTIAL_ERROR"
    else:
        goal_status = "COMPLETE"
    return {
        "goal_id": goal_id,
        "title": goal.get("title", ""),
        "status": goal_status,
        "step_count": len(steps),
        "ok": statuses.count("OK"),
        "blocked": statuses.count("BLOCKED"),
        "errored": statuses.count("ERROR"),
    }


# --------------------------------------------------------------------------
# Checkpoint / report generator
# --------------------------------------------------------------------------
def build_checkpoint(goal_results: list, ledger: Ledger) -> dict:
    entries = ledger.read_all()
    return {
        "generated_ts": now_iso(),
        "checkpoint_kind": "6h-cadence-compatible",
        "goals_total": len(goal_results),
        "goals_complete": sum(1 for g in goal_results if g["status"] == "COMPLETE"),
        "steps_ok": sum(1 for e in entries if e.get("status") == "OK"),
        "steps_blocked": sum(1 for e in entries if e.get("status") == "BLOCKED"),
        "steps_errored": sum(1 for e in entries if e.get("status") == "ERROR"),
        "guardrail_blocks": [
            {"seq": e["seq"], "step_id": e.get("step_id"), "reason": e.get("guardrail_reason")}
            for e in entries
            if e.get("status") == "BLOCKED"
        ],
        "goal_results": goal_results,
        "ledger_entries": len(entries),
    }


def write_checkpoint_md(checkpoint: dict, path: str) -> None:
    lines = [
        "# Harness Checkpoint Report",
        "",
        f"- Generated: {checkpoint['generated_ts']}",
        f"- Cadence: {checkpoint['checkpoint_kind']}",
        f"- Goals: {checkpoint['goals_complete']}/{checkpoint['goals_total']} complete",
        f"- Steps OK: {checkpoint['steps_ok']} | Blocked: {checkpoint['steps_blocked']} | Errored: {checkpoint['steps_errored']}",
        f"- Ledger entries: {checkpoint['ledger_entries']}",
        "",
        "## Guardrail blocks (hard-stop enforcement)",
    ]
    if checkpoint["guardrail_blocks"]:
        for b in checkpoint["guardrail_blocks"]:
            lines.append(f"- seq {b['seq']} step `{b['step_id']}`: {b['reason']}")
    else:
        lines.append("- none")
    lines += ["", "## Goal results"]
    for g in checkpoint["goal_results"]:
        lines.append(
            f"- `{g['goal_id']}` {g['title']}: {g['status']} "
            f"(ok={g['ok']} blocked={g['blocked']} err={g['errored']})"
        )
    lines.append("")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


# --------------------------------------------------------------------------
# Orchestration entrypoint
# --------------------------------------------------------------------------
def run(goals_path: str, out_dir: str) -> dict:
    os.makedirs(out_dir, exist_ok=True)
    ledger = Ledger(os.path.join(out_dir, "action_ledger.jsonl"))
    goals = load_goals(goals_path)
    goal_results = [run_goal(g, ledger) for g in goals]
    checkpoint = build_checkpoint(goal_results, ledger)
    with open(os.path.join(out_dir, "checkpoint.json"), "w", encoding="utf-8") as fh:
        json.dump(checkpoint, fh, indent=2, sort_keys=True)
    write_checkpoint_md(checkpoint, os.path.join(out_dir, "checkpoint.md"))
    return checkpoint


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Cognitia file-based goal-loop harness (MOCK MVP)")
    parser.add_argument("--goals", required=True, help="Path to goals JSON file")
    parser.add_argument("--out", required=True, help="Output directory for ledger + checkpoint")
    ns = parser.parse_args(argv)
    checkpoint = run(ns.goals, ns.out)
    print(json.dumps(
        {
            "goals_complete": checkpoint["goals_complete"],
            "goals_total": checkpoint["goals_total"],
            "steps_ok": checkpoint["steps_ok"],
            "steps_blocked": checkpoint["steps_blocked"],
            "steps_errored": checkpoint["steps_errored"],
            "out_dir": ns.out,
        },
        indent=2,
    ))
    return 0


if __name__ == "__main__":
    sys.exit(main())
